dist: xenial   # required for Python >= 3.7
language: python
python: "3.7"
before_install:
  - pip install poetry~=0.12.17
install:
  # we run `poetry version` here to appease poetry about '0.0.0-source'
  - poetry version
  - poetry install
script:
  - poetry run python --version
  - poetry run behave
before_deploy:
  - pip install poetry~=0.12.17
  - poetry config http-basic.pypi $PYPI_USER $PYPI_PASS
  - poetry version $TRAVIS_TAG
  - poetry build
deploy:
  - provider: script
    script: poetry publish
    skip_cleanup: true
    on:
      branch: master
      tags: true
