language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  # - "nightly"
  - "pypy2.7"
  - "pypy3.5"
install:
  - "pip install setuptools -U"
  - "pip install -e ."
  - "pip install -q behave"
# command to run tests
script:
 - python --version
 - behave

 matrix:
  allow_failures:
    python: "3.7-dev"
    # python: "nightly"
    python: "pypy2.7"
    python: "pypy3.5"
sudo: false
cache: pip
