language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install: "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: nosetests
matrix:
  allow_failures: # python 3 support for travis is shaky....
    - python: 3.3
