language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - "pip install -e ."
  - "pip install pycrypto>=2.6"
  - "pip install -q behave"
# command to run tests
script:
 - python --version
 - behave
